name: "Chromatic"

on: 
  pull_request:

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install action dependencies
        run: cd .github/actions/chromatic && yarn install --immutable
      - name: Publish Catapa UI to Chromatic
        uses: chromaui/action@latest
        id: chromatic
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: build:chromatic-storybook
      - name: Manage PR comments
        if: success() && github.event_name == 'pull_request'
        uses: ./.github/actions/chromatic
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          storybook-url: ${{ steps.chromatic.outputs.storybookUrl }}
          build-url: ${{ steps.chromatic.outputs.buildUrl }}

